app/blueprints/views.py
from typing import Optional

from flask import Blueprint, jsonify, render_template, request

from app.blueprints.post_blueprint.dao.post_dao import File, Post
from app.logger import logger

post_blueprint = Blueprint('post_blueprint', __name__, template_folder='templates')


@post_blueprint.route('/', methods=['GET'])
def main_page():
    posts = File().get_all_posts()
    return render_template('index.html', posts=posts)


@post_blueprint.route('/post/<int:post_id>', methods=['GET'])
def post_page(post_id: int):
    post_by_id: Optional[dict] = Post().get_post_by_id(post_id)
    comments_by_id: list[dict] = Post().get_comments(post_id)
    return render_template('post.html', post_by_id=post_by_id, comments_by_id=comments_by_id)


@post_blueprint.route('/search/', methods=['GET'])
def search_page():
    search_word: str = request.args.get('search_word')
    print(search_word)
    posts_by_word = Post().search_posts_by_word(search_word)
    return render_template('search.html', posts_by_word=posts_by_word)


@post_blueprint.route('/users/<username>')
def user_page(username: str):
    posts = Post().search_posts_by_user(username)
    return render_template('user-feed.html', posts=posts)


# API
@post_blueprint.route('/api/post')
def api_all_post():
    posts = File().get_all_posts()
    logger.info('Request /api/post')
    return jsonify(posts)


@post_blueprint.route('/api/post/<int:post_id>')
def api_post(post_id: int):
    post_by_id: Optional[dict] = Post().get_post_by_id(post_id)
    logger.info(f'Request /api/post/{post_id}')
    return jsonify(post_by_id)

app/blueprints/templates/post.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SKYPROGRAM post</title>
  <link href="{{ url_for('static', filename='css/styles.min.css') }}" rel="stylesheet">
</head>

<body>
  <header class="container header">
    <div class="header__wrapper">
      <a href="{{ url_for('post_blueprint.main_page') }}" class="header__btn-back">
        <svg class="header__btn-icon" width="19" height="16">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
        </svg>
      </a>
      <a href="{{ url_for('post_blueprint.main_page') }}" class="header__logo-link">
        <svg class="header__logo" width="64" height="26">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#post"></use>
        </svg>
      </a>
    </div>
  </header>

  <main class="container">
    <section class="items">
      <div class="items__item item item--post">
        <div class="item__top">
          <a href="{{ url_for('post_blueprint.main_page')}}" class="item__head">
            <div class="item__ava-wrap">
              <img src="{{ post_by_id.poster_avatar }}" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">{{ post_by_id.poster_name }}</span>
          </a>
          <button type="button" class="item__bookmark-btn">
            <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
        <a href="" class="item__post-link">
          <img src="{{ post_by_id.pic }}" alt="" width="348" class="item__post-img">
        </a>
        <div class="item__descr">
          <p class="item__text">
            {{ post_by_id.content }}
          </p>
        </div>

        <div class="item__bottom">
          <div class="item__post-info">
            <p class="item__comments-counter"> {{ comments_by_id|length }} комментария </p>
            <div class="item__counter">
              <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
              <span class="item__counter-text">{{ post_by_id.views_count }}</span>
            </div>
          </div>
            <div class="item__comments">

              {%  for comm in comments_by_id %}
                    <p class="item__comment">
                      <b>{{ comm.commenter_name }}</b> {{ comm.comment }}
                    </p>
              {% endfor %}
          </div>


        </div>
      </div>
    </section>
  </main>
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="post" viewbox="0 0 64 26" fill="none" width="64" height="26">
      <path d="M5.88 25v-8.48h2.208c4.416 0 7.232-2.528 7.232-7.2V8.04C15.32 3.432 12.504 1 8.088 1H.6v24h5.28ZM7.832 5.48c1.536 0 2.432.768 2.432 2.88V9c0 2.176-.896 3.04-2.432 3.04H5.88V5.48h1.952Zm17.257 20c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52ZM35.243 6.952c0 3.264 1.44 5.184 3.52 6.752l2.56 1.952c1.664 1.28 2.624 2.016 2.624 3.648 0 1.152-.704 1.856-1.888 1.856-1.152 0-1.92-.896-1.92-2.304V17h-5.12v2.08c0 4.128 3.168 6.4 7.04 6.4s7.04-2.24 7.04-6.816c0-3.104-1.536-5.056-3.584-6.592l-2.656-2.048c-1.568-1.184-2.496-1.888-2.496-3.456 0-1.12.704-1.728 1.664-1.728 1.056 0 1.728.704 1.728 2.176V8.68h5.024V6.92c0-4.32-2.976-6.4-6.752-6.4-3.712 0-6.784 1.824-6.784 6.432ZM59.414 25V5.64h3.904V1H50.07v4.64h3.904V25h5.44Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
</body>

</html>

app/blueprints/templates/search.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SKYPROGRAM search</title>
  <link href="{{ url_for('static', filename='css/styles.min.css') }}" rel="stylesheet">
</head>

<body>
  <header class="container header">
    <div class="header__wrapper">
      <a href="/" class="header__btn-back">
        <svg class="header__btn-icon" width="19" height="16">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
        </svg>
      </a>
      <a href="/" class="header__logo-link">
        <svg class="header__logo" width="100" height="26">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#search"></use>
        </svg>
      </a>
    </div>
  </header>


  <main class="container">
    <div class="search">

      <p class="search__results">Найдено постов: {{ posts_by_word|length }}</p>
    </div>

    <section class="items">
        {%  for post in posts_by_word %}
          <div class="items__item item">
            <div class="item__top">
              <a href="{{ url_for('post_blueprint.user_page', username=post.poster_name) }}" class="item__head">
                <div class="item__ava-wrap">
                  <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
                </div>
                <span class="item__username"> {{ post.poster_name }}</span>
              </a>
            </div>
            <a href="{{ url_for('post_blueprint.post_page', post_id=post.pk) }}" class="item__post-link">
              <img src="{{ post.pic }}" alt="" width="348" class="item__post-img">
            </a>
            <p class="item__descr"><a href="/tag.html" class="item__tag">#food</a> {{ post.content[:50] }}.</p>
            <div class="item__post-info">
              <div class="item__counter">
                <img src="{{ url_for('static', filename='img/eye.png') }}" alt="" class="item__counter-icon" width="26">
                <span class="item__counter-text">{{ post.views_count }}</span>
              </div>
            </div>
            <div class="item__post-bottom">
              <a href="{{ url_for('post_blueprint.post_page', post_id=post.pk) }}" class="item__btn-more">Подробнее</a>
              <button type="button" class="item__bookmark-btn">
                <img src="{{ url_for('static', filename='img/bookmark.png') }}" alt="" class="item__bookmark-icon" width="24">
              </button>
            </div>
          </div>
        {% endfor %}

    </section>
  </main>
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="search" viewbox="0 0 100 26" fill="none" width="100" height="26">
      <path d="M1.024 6.952c0 3.264 1.44 5.184 3.52 6.752l2.56 1.952c1.664 1.28 2.624 2.016 2.624 3.648 0 1.152-.704 1.856-1.888 1.856-1.152 0-1.92-.896-1.92-2.304V17H.8v2.08c0 4.128 3.168 6.4 7.04 6.4s7.04-2.24 7.04-6.816c0-3.104-1.536-5.056-3.584-6.592L8.64 10.024C7.072 8.84 6.144 8.136 6.144 6.568c0-1.12.704-1.728 1.664-1.728 1.056 0 1.728.704 1.728 2.176V8.68h5.024V6.92c0-4.32-2.976-6.4-6.752-6.4-3.712 0-6.784 1.824-6.784 6.432ZM29.099 20.36h-6.592v-5.28h5.952v-4.64h-5.952v-4.8H29.1V1H17.131v24H29.1v-4.64ZM34 1l-3.777 24h5.216l.576-4.32h4.416l.577 4.32h5.215L42.447 1H34Zm2.623 15.2 1.6-11.68 1.6 11.68h-3.2ZM53.352 25V13.192L57.671 25h5.984l-4.64-11.104c2.432-.832 4.032-2.752 4.032-5.728V7.24c0-4.064-2.976-6.24-7.072-6.24h-8v24h5.376Zm1.888-19.52c1.504 0 2.432.704 2.432 2.688v.448c0 2.144-.928 3.008-2.432 3.008h-1.888V5.48h1.888Zm20.25 9.28v2.56c0 2.624-.896 3.52-2.4 3.52s-2.4-.896-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v2.24h5.44V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32s7.84-2.752 7.84-8.32v-2.4h-5.44ZM89.259 25v-9.984h4.8V25h5.44V1h-5.44v9.344h-4.8V1h-5.44v24h5.44Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
</body>

</html>

app/blueprints/templates/tag.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SKYPROGRAM tag</title>
  <link href="../static/css/styles.min.css" rel="stylesheet">
</head>

<body>
  <header class="container header">
    <div class="header__wrapper">
      <a href="/app/blueprints/static" class="header__btn-back">
        <svg class="header__btn-icon" width="19" height="16">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
        </svg>
      </a>
      <a href="#" class="header__nosvg">
        ТЭГ / ЕДА
      </a>
    </div>
  </header>
  <main class="container">
    <section class="items">
      <div class="items__item item">
        <div class="item__top">
          <a href="/app/blueprints/templates/user-feed.html-feed.html" class="item__head">
            <div class="item__ava-wrap">
              <img src="../static/img/ava1.png" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">Username</span>
          </a>
        </div>
        <a href="/app/blueprints/templates/post.html/post.html" class="item__post-link">
          <img src="../static/img/post4.jpg" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr"><a href="/app/blueprints/post_blueprint/templatesrints/post_blueprint/templates/tag.html" class="item__tag">#food</a> Текст описания коротки...</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="../static/img/eye.png" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">212</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="/app/blueprints/templates/post.html/post.html" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn">
            <img src="../static/img/bookmark.png" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
      <div class="items__item item">
        <div class="item__top">
          <a href="/app/blueprints/templates/user-feed.html-feed.html" class="item__head">
            <div class="item__ava-wrap">
              <img src="../static/img/ava2.png" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">Username</span>
          </a>
        </div>
        <a href="/app/blueprints/templates/post.html/post.html" class="item__post-link">
          <img src="../static/img/post2.jpg" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr"><a href="/app/blueprints/post_blueprint/templatesrints/post_blueprint/templates/tag.html" class="item__tag">#food</a> Текст описания коротки...</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="../static/img/eye.png" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">1023</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="/app/blueprints/templates/post.html/post.html" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn active">
            <img src="../static/img/bookmark.png" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
      <div class="items__item item">
        <div class="item__top">
          <a href="/app/blueprints/templates/user-feed.html-feed.html" class="item__head">
            <div class="item__ava-wrap">
              <img src="../static/img/ava2.png" alt="" class="item__ava" width="47">
            </div>
            <span class="item__username">Username</span>
          </a>
        </div>
        <a href="/app/blueprints/templates/post.html/post.html" class="item__post-link">
          <img src="../static/img/post3.jpg" alt="" width="348" class="item__post-img">
        </a>
        <p class="item__descr"><a href="/app/blueprints/post_blueprint/templatesrints/post_blueprint/templates/tag.html" class="item__tag">#food</a> Текст описания коротки...</p>
        <div class="item__post-info">
          <div class="item__counter">
            <img src="../static/img/eye.png" alt="" class="item__counter-icon" width="26">
            <span class="item__counter-text">1023</span>
          </div>
        </div>
        <div class="item__post-bottom">
          <a href="/app/blueprints/templates/post.html/post.html" class="item__btn-more">Подробнее</a>
          <button type="button" class="item__bookmark-btn">
            <img src="../static/img/bookmark.png" alt="" class="item__bookmark-icon" width="24">
          </button>
        </div>
      </div>
    </section>
  </main>
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="tag" viewbox="0 0 144 26" fill="none" width="144" height="26">
      <path d="M9.664 25V5.64h3.904V1H.32v4.64h3.904V25h5.44Zm7.178-24-3.776 24h5.216l.576-4.32h4.416L23.85 25h5.216L25.29 1h-8.448Zm2.624 15.2 1.6-11.68 1.6 11.68h-3.2Zm17.532 9.28c2.273 0 4.033-.928 5.056-2.848V25h3.968V12.04h-8.16v4.32h2.72v1.12c0 2.464-.928 3.36-2.4 3.36-1.504 0-2.4-.896-2.4-3.52V8.68c0-2.656.929-3.52 2.4-3.52 1.505 0 2.4.864 2.4 3.52v1.344h5.44V8.84c0-5.568-2.975-8.32-7.84-8.32-4.864 0-7.84 2.752-7.84 8.32v8.32c0 5.568 2.56 8.32 6.657 8.32ZM59.58 25l8-24h-3.84l-8 24h3.84Zm23.24 0v-9.28h5.472v-4.64H82.82V5.64h6.272V1H77.444v24h5.376Zm16.019.48c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52Zm18.25 4.64c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52ZM135.339 1h-7.52v24h7.52c4.864 0 7.84-2.688 7.84-8.16V9.16c0-5.472-2.976-8.16-7.84-8.16Zm0 19.36h-2.08V5.64h2.08c1.504 0 2.4.832 2.4 3.36v8c0 2.528-.896 3.36-2.4 3.36Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
</body>

</html>